version: "3"

services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "-C", "pg_isready -U @POSTGRES_USER"]
      interval: 10s
      retries: 3
      timeout: 5s
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  celery:
    build: .
    tty: true
    command: celery -A atomic_habits worker -l INFO
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env

  celery-beats:
    build: .
    tty: true
    command: celery -A atomic_habits beat -l INFO
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env
volumes:
  pg_data: